# Generated by Django 6.0.5 on 2026-05-19 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Unit_price',
            new_name='price',
        ),
    ]
